.TH "IRIS-CONFIG-PARSER" 1 "2013-04-03" "Iris TCP server" "Iris TCP server"

.SH NAME
iris\-config\-parser \- Iris TCP server configuration parser
.SH "SYNOPSIS"
.PP
\fBiris\-config\-parser\fR \fIconfig\fR
.SH "DESCRIPTION"
.PP
iris\-config\-parser is a program to check syntax of iris\-server configuration file. It prints formatted configuration file to standard output.
.SH "OPTIONS"
.TP
.BI config
Check and print specified configuration file\&.
.SH AUTHOR
Written by Communico, LLC.
.SH "REPORTING BUGS"
Report all bugs to iris\-bugs@communico.pro
.br
Iris home page: <http://www.communico.pro/iris/>
.SH COPYRIGHT
Copyright \(co 2013-2014 Iris Dev. team. All rights reserved.
.br
License: see <http://www.communico.pro/license/>.
.SH SEE ALSO
.BR iris\-config\-test (8),
.BR iris\-server (8),
.BR /usr/share/doc/iris-0.1-core/README.Debian.gz
.
