.TH "IRIS-CONFIG-TEST" 1 "2013-04-03" "Iris SMTP/LMTP/POP3/IMAP4 server" "Iris SMTP/LMTP/POP3/IMAP4 server"

.SH NAME
iris\-config\-test \- Iris SMTP/LMTP/POP3/IMAP4 server configuration test tool
.SH "SYNOPSIS"
.PP
\fBiris\-config\-test\fR \fIconfig\fR
.SH "DESCRIPTION"
.PP
iris\-config\-test is a program to check configuration of iris\-server. It parses the configuration files, checks existence and permissions of loadable modules. This test does not catch all errors.
.SH "OPTIONS"
.TP
.BI config
Check and specified configuration file\&.
.SH AUTHOR
Written by Communico, LLC.
.SH "REPORTING BUGS"
Report ls bugs to iris\-bugs@communico.pro
.br
Iris home page: <http://www.communico.pro/iris/>
.SH COPYRIGHT
Copyright \(co 2013 Iris Dev. team. All rights reserved.
.br
License: see <http://www.communico.pro/license/>.
.SH SEE ALSO
.BR iris\-config\-test (8),
.BR iris\-server (8),
.BR /usr/share/doc/iris-0.0-core/README.Debian.gz
.
